### ISSUE TITLE
Install on RS217 fails

### ISSUE THREAD

**Issue by e2bady** [flipswitchingmonkey/gitea-spk#14]
Used Computer: Windows 10 machine
User Synology: RS217

Steps to reproduce:

$ git clone https://github.com/flipswitchingmonkey/gitea-spk.git
$ cd gitea-spk
download https://github.com/go-gitea/gitea/releases/download/v1.2.1/gitea-1.2.1-linux-arm-7
$ ./create_spk.sh
Install Git-Server
Enable SSH
Start Git-Server
Go to Manual Installation
Choose: gitea-1.2.1-linux-arm-7.spk
After pressing next, it shows an error message that the paket is not compatible with the DSM-Version.

Any thoughts?

**Comment by flipswitchingmonkey** [comment]
Probably has to do with the armada38x support (which was just merged in). Maybe give it a try now.

**Comment by e2bady** [comment]
The installation worked. Thank you. 

#14 fixed.
