### ISSUE TITLE
Running on DS216 Play

### ISSUE THREAD

**Issue by andxet** [flipswitchingmonkey/gitea-spk#17]
Does anyone tried to run this on 216 Play? I tried with the ARMv7 binary but SDM says that it isn't compatible.

**Comment by flipswitchingmonkey** [comment]
I don't have one to test it on, sorry.

**Comment by flipswitchingmonkey** [comment]
Apparently it's a variant of the usual ARM cpus they use: http://www.synology-wiki.de/index.php/Welchen_Prozessortyp_besitzt_mein_System%3F
"STM Monaco ARM"

From what I can find, you need a version compiled for Alpine ARM7. Not familiar with that myself though.

**Comment by andxet** [comment]
Thank you for the answer.
Where do you found what you said in the last line? I can't find anything useful about this architecture

**Comment by andxet** [comment]
Ok I found that it runs if you download armv7 version and run it from the terminal. now I try to figure out how to make it compatible as spk package

**Comment by andxet** [comment]
Solved: just add "monaco" in the file arch.desc in the line that starts with armv7

**Comment by flipswitchingmonkey** [comment]
merged.
